version: '3.8'

services:
  redis:
    image: redis:alpine

  currency_service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: ["python", "currency_service.py"]

  bot_service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - BOT_TOKEN=7013260741:AAHwjBU7kPuvx0-P9AuUBmLXczuTDeBJm6k
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: ["python", "bot_service.py"]
