version: '3.8'

services:
  redis:
    image: redis:alpine

  currency_service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - XML_URL=${XML_URL}
    command: ["python", "currency_service.py"]

  bot_service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    command: ["python", "bot_service.py"]
